//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub organizer_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub kind: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub pokemon_event_slug: String,
    pub guid: Uuid,
    pub league: Option<i32>,
    pub happening_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "organizer_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub organizers: HasOne<super::organizers::Entity>,
    #[sea_orm(has_many)]
    pub user_subscription_notifications: HasMany<super::user_subscription_notifications::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
