//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "organizers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub city: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub area: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub country: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub latitude: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub longitude: f64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub events: HasMany<super::events::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
