//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_subscription_notifications")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_subscription_id: i32,
    pub event_id: i32,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "event_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub events: HasOne<super::events::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_subscription_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user_subscriptions: HasOne<super::user_subscriptions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
